language: go
services:
  - docker
script:
  - docker-compose build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push guamulo/dockerimagesave:${TRAVIS_BUILD_NUMBER}
