language: go
go:
- "1.14"
services:
- docker
script:
- go test
- docker-compose build
- /bin/bash build_executables.sh
- docker tag guamulo/dockerimagesave:${TRAVIS_BUILD_NUMBER} guamulo/dockerimagesave:latest
- echo working on branch ${TRAVIS_BRANCH}
- if [[ ${TRAVIS_BRANCH} == master ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
- if [[ ${TRAVIS_BRANCH} == master ]]; then docker push guamulo/dockerimagesave:${TRAVIS_BUILD_NUMBER}; docker push guamulo/dockerimagesave:latest; fi



deploy:
  provider: releases
  api_key:
    secure: cVqdTu3nY54hSwDch9Jm5umGO4WRUK30wgTwGNit6jXZWb+S6pVWW2OdHnSko10CF0tMThIB88NeJYmtimjX9uPWTX9jcL4z9GZv87d6BsMSPSfFGbLAXE1qN9g2CsCqQ8ysDo5ydSN46qN0kj+EZkZKqfkler76CtaKh4O0DDxklNQzJNC7jTJkJVFfZgL0nJ34nvgsEC6CWmgkrd1Y1zpN6R9zv1lsu5beWO734hw0wFYiFdyR9jfPoVi50X8D1m7p/s50ggckkx68Flb3HW+42L/JP+9wAc/ODThkEDjfrS96uRHXqxkqYDbDlgsTOtpWmHPGcfqt70t+PFcp13aAbzLxlB8x/VvNtVyabm70BRDCtujqOKaFywrgC/P16/nX6QD6blGcg/Vbeg4DdfEZtcAqDQsslAq4rXEwYOg7dw/L+iBuLB2VuaibzHk0fGu5StNSSBigrXs17/nctExIGX3FsmnfCo/m3XTc75y3xp6nfp9u7EnMVd/6OGTtHdUTy1IqS2MgJ5QtqENZZyatCKzNt6XfcKa0he3wLaOKzo/wubDqm/wWWVcB9OSoDDjZmqyzb2c78UrMhIT/Aiwd8H2ujo9jBJ/emTEWvI+9dZyFowHbTzhiBLj90J9HOFeGKCpAZdYkHjHYlhWH7tgzfxg2zUPRap0iShGW9L0=
  file:
    - "DockerImageSave-linux-amd64"
    - "DockerImageSave-darwin-amd64"
    - "DockerImageSave-windows-amd64.exe"
  skip_cleanup: true
  on:
    tags: true
