version: "3"
services: 
  dockerimagesave:
    build: .
    ports: 
      - 6060:6060
    image: guamulo/dockerimagesave:${TRAVIS_BUILD_NUMBER}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
