version: "3"
services: 
  dockerimagesave:
    build: .
    ports: 
      - 6060:6060
    image: dockerimagesave
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
