[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/docker/docker"
  revision = "a422774e593b33bd287d9890544ad9e09b380d8c"
