[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.7.0"

[[constraint]]
  name = "github.com/cavaliercoder/grab"
  version = "2.0.0"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "1.4.4"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/kyokomi/emoji"
  version = "2.1.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.19.8"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
